### ISSUE TITLE
Sequelize doesn't support pg7

### ISSUE THREAD

**Issue by JustinBis** [Nevon/serverless-pg-migrations#1]
Sequelize currently is broken when using pg7 (see https://github.com/sequelize/sequelize/issues/7998). serverless-pg-migrations depends on pg@^7.0.2, but this should be some pg6 version instead to support Sequelize in its current state.

**Comment by Nevon** [comment]
Thanks for letting me know. I'm not currently using serverless-pg-migrations in production, but it's curious that I didn't have a problem during development, as I was able to run migrations without any problem.

Either way, could you leave a 👍 on the PR if you think it adequately solves your issue, and I'll push out an update with this fixed.
